(defparameter *cl-redis-kit-core-source-files*
  '("package.lisp"
    "keyword-options.lisp"
    "conditions.lisp"
    "condition-report.lisp"
    "protocol-model.lisp"
    "protocol-values.lisp"
    "protocol-reader.lisp"
    "protocol-scalar-decoder.lisp"
    "protocol-aggregate-decoder.lisp"
    "protocol-api.lisp"
    "protocol-encoder.lisp"
    "metrics-api.lisp"
    "metrics.lisp"
    "tls-api.lisp"
    "tls.lisp"
    "connection-model-data.lisp"
    "connection-model.lisp"
    "execution-journal-api.lisp"
    "execution-journal.lisp"
    "connection-transport.lisp"
    "connection-lifecycle.lisp"
    "connection-policy-api.lisp"
    "connection-policy.lisp"
    "connection-pipeline.lisp"
    "connection-scope-api.lisp"
    "connection-scope.lisp"
    "command-data-model.lisp"
    "command-data-registration.lisp"
    "command-data.lisp"
    "command-spec.lisp"
    "command-helpers.lisp"
    "commands-connection.lisp"
    "commands-key-value-declarations.lisp"
    "commands-key-value.lisp"
    "commands-collections-declarations.lisp"
    "commands-collections.lisp"
    "pool-model-data.lisp"
    "pool-model.lisp"
    "pool.lisp"
    "pool-api.lisp"))

(defun cl-redis-kit-core-source-pathnames (source-directory)
  (mapcar (lambda (name)
            (merge-pathnames name source-directory))
          *cl-redis-kit-core-source-files*))
