(defun eval (connection script keys &rest arguments)
  (unless (listp keys)
    (error 'redis-client-error :message "EVAL KEYS must be a list." :cause keys))
  (multiple-value-bind (command-arguments options)
      (%split-options arguments '(:decode :timeout :retry-safe-p))
    (%command-value connection "EVAL"
                    (append (list script (length keys)) keys command-arguments)
                    :decode (getf options :decode :utf-8)
                    :timeout (getf options :timeout)
                    :retry-safe-p (getf options :retry-safe-p))))
