(defun register-redis-command-specification (specification)
  (check-type specification redis-command-spec)
  (setf (gethash (redis-command-spec-name specification)
                 *redis-command-specifications*)
        specification))
