(defpackage #:redis-kit
  (:use #:cl)
  (:shadow #:eval #:get #:set)
  (:export
   ;; Protocol values and codec
   #:redis-reply
   #:redis-reply-p
   #:redis-reply-type
   #:redis-reply-value
   #:redis-reply-attributes
   #:decode-reply
   #:read-reply
   #:encode-command
   #:encode-commands
   #:reply-value
   #:reply-error-p
   #:null-reply-p
   #:*default-max-line-length*
   #:*default-max-bulk-length*
   #:*default-max-array-length*
   #:*default-max-depth*
   #:*default-max-frame-size*
   ;; Conditions
   #:redis-error
   #:redis-client-error
   #:redis-protocol-error
   #:redis-connection-error
   #:redis-timeout-error
   #:redis-server-error
   #:redis-error-message
   #:redis-error-cause
   #:redis-error-code
   #:redis-error-reply
   #:redis-error-position
   ;; Connections
   #:redis-connection
   #:redis-connection-p
   #:make-connection
   #:open-connection
   #:close-connection
   #:connection-open-p
   #:connection-state
   #:connection-host
   #:connection-port
   #:connection-protocol
   #:connection-timeout
   #:connection-tls
   #:connection-retry-policy
   #:connection-metric-registry
   #:connection-metrics-snapshot
   #:call-with-connection
   #:with-connection
   #:execute-reply
   #:execute
   #:pipeline-replies
   #:pipeline
   #:drain-pushes
   #:connection-network-boundary
   ;; Instrumentation
   #:redis-metrics
   #:redis-metrics-p
   #:make-redis-metrics
   #:redis-metrics-registry
   #:redis-metrics-snapshot
   ;; Command specifications
   #:define-redis-command
   #:redis-command-spec
   #:redis-command-spec-p
   #:redis-command-spec-name
   #:redis-command-spec-command
   #:redis-command-spec-lambda-list
   #:redis-command-spec-arguments
   #:redis-command-spec-decode
   #:redis-command-spec-timeout
   #:redis-command-spec-retry-safe-p
   #:redis-command-specification
   #:redis-command-specification-names
   ;; Connection-level commands
   #:auth
   #:select
   #:hello
   #:ping
   #:quit
   ;; Common commands
   #:get
   #:set
   #:del
   #:exists
   #:incr
   #:decr
   #:expire
   #:pexpire
   #:ttl
   #:pttl
   #:hget
   #:hset
   #:hdel
   #:lpush
   #:rpush
   #:lrange
   #:sadd
   #:smembers
   #:zadd
   #:zrange
   #:publish
   #:flushdb
   #:eval
   ;; Pools
   #:redis-pool
   #:redis-pool-p
   #:make-pool
   #:close-pool
   #:pool-closed-p
   #:pool-size
   #:pool-idle-count
   #:pool-max-size
   #:pool-max-wait
   #:call-with-pool-connection
   #:pool-execute
   #:with-pool))
